#!/usr/bin/env python3
"""
Generate a helper shell script to create and configure the TUN interface for PQVPN.
Writes /tmp/pqvpn_setup_tun.sh (executable) by default.
Usage: python scripts/generate_tun_setup.py --config config.yaml --out /tmp/pqvpn_setup_tun.sh
"""

import argparse
import yaml
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument("--config", "-c", default="config.yaml")
parser.add_argument("--out", "-o", default="/tmp/pqvpn_setup_tun.sh")
args = parser.parse_args()

cfg_path = Path(args.config)
if not cfg_path.exists():
    print(f"Config file not found: {cfg_path}")
    raise SystemExit(1)

text = cfg_path.read_text(errors="replace")
try:
    data = yaml.safe_load(text) or {}
except Exception as e:
    print(f"Failed to parse YAML: {e}")
    raise SystemExit(1)

plugins = data.get("plugins", {}) or {}
# support legacy top-level 'tun' mapping
if "tun" in data and not plugins.get("tun"):
    plugins["tun"] = data.get("tun") or {}

tun = plugins.get("tun", {}) or {}
device = tun.get("device") or tun.get("dev") or tun.get("device_name") or "pqvpn0"
cidr = tun.get("cidr") or tun.get("address") or tun.get("ip") or ""
up_cmd = tun.get("up_cmd") or tun.get("upcmd") or ""
apply_routes = bool(tun.get("apply_routes", False))
route_via = tun.get("route_via") or ""

out_path = Path(args.out)
lines = []
lines.append("#!/bin/sh")
lines.append("# Generated by scripts/generate_tun_setup.py")
lines.append("# Run this as root: sudo /tmp/pqvpn_setup_tun.sh")
lines.append("set -u")
lines.append("")
# create tuntap device; tolerate already-exists
lines.append(f'echo "Creating TUN device {device} (idempotent)"')
lines.append(f"ip tuntap add dev {device} mode tun 2>/dev/null || true")
if up_cmd:
    lines.append('echo "Running custom up_cmd"')
    # run as shell
    lines.append(up_cmd + ' || { echo "up_cmd failed"; exit 1; }')
else:
    if cidr:
        lines.append(f'echo "Adding IP {cidr} to {device}"')
        # try to add, if fails try replace; keep tolerant
        lines.append(
            f"ip addr add {cidr} dev {device} 2>/dev/null || ip addr replace {cidr} dev {device} || true"
        )
    lines.append(f'echo "Bringing {device} up"')
    lines.append(f"ip link set dev {device} up 2>/dev/null || true")

if apply_routes:
    if route_via:
        lines.append(f'echo "Setting default route via {route_via} dev {device}"')
        lines.append(f"ip route replace default via {route_via} dev {device} || true")
    else:
        # Safe default: do not automatically replace the system default route when route_via is not provided.
        lines.append(
            'echo "apply_routes requested but no route_via provided: skipping automatic default route replacement (safe default)"'
        )
        lines.append(
            "# To force replacing the default route via this device, edit this script and uncomment the following line:"
        )
        lines.append(f"# ip route replace default dev {device} || true")

lines.append('echo "TUN setup complete."')

out_path.write_text("\n".join(lines) + "\n")
try:
    out_path.chmod(0o750)
except Exception:
    pass
print(f"Wrote {out_path} (run as root to apply):")
print("\n".join(lines))
